language: objective-c
osx_image:
  - xcode9
before_install:
  - brew update
  - brew install nvm > /dev/null 2>&1
before_script:
  - source $(brew --prefix nvm)/nvm.sh
  - nvm install 8
script:
  - npm i
  - npm run ci
